#!/usr/bin/env python3
"""
pipeline.py - runs the 6-phase SDLC with a human gate at each phase, and fires
the tool integrations AFTER the relevant gate. Flow is unchanged; integrations
are optional (dry-run safe).

  intake -> po (->Jira) -> code (->GitHub PR) -> test -> pr (->PR findings)
         -> HITL approve -> merge

Usage:
  python pipeline.py --in demo/transcript.txt          # interactive gates
  python pipeline.py --in demo/transcript.txt --auto   # no prompts (demo dry-run)
"""
import argparse, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "agents"))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "integrations"))
import agents, llm

INPUTS = {
    "intake": [], "po": ["intake"], "code": ["po"],
    "test": ["po", "code"], "pr": ["po", "code", "test"], "release": ["po", "pr"],
}

def gate(a, auto):
    print("\n" + "="*66)
    print(f"HUMAN GATE - {a.title} ({a.phase})\n  {a.gate}")
    print("="*66)
    if auto:
        print("  [--auto] approved.")
        return "a"
    while True:
        c = input("  [a]pprove  [r]egenerate  [q]uit > ").strip().lower() or "a"
        if c in ("a", "r", "q"):
            return c
        print("  choose a/r/q")

# ---- integration hooks (fire AFTER the phase gate) -----------------------
def _parse_po_json(md):
    """Deterministic path: read the ## Backlog JSON block the PO agent emits."""
    import json
    m = re.search(r"```json\s*(\{.*?\})\s*```", md, re.S)
    if not m:
        return None
    try:
        d = json.loads(m.group(1))
        epic = (d.get("epic") or "").strip()
        stories = [s.strip() for s in d.get("stories", []) if s and s.strip()]
        if epic and stories:
            return epic, stories
    except Exception:
        pass
    return None

def after_po(artifacts):
    from jira_client import JiraClient, BacklogItem
    parsed = _parse_po_json(artifacts["po"])
    if parsed:
        epic, stories = parsed
    else:  # fallback to heuristic parse of the prose
        epic = _first_line(artifacts["po"], "## Epic") or "Backlog epic"
        stories = _bullets(artifacts["po"], "## User Stories")[:4]
    try:
        res = JiraClient().create_epic_and_stories(BacklogItem(epic=epic, stories=stories))
        loc = f" -> {res.url}" if res.url else ""
        print(f"  -> Jira: Epic {res.epic_key}, Stories {res.story_keys}" + (" (dry-run)" if res.dry_run else loc))
    except SystemExit as e:
        print(f"  -> Jira skipped: {e}")
    except Exception as e:
        print(f"  -> Jira error (continuing): {e}")

def after_code(artifacts, state):
    from github_client import GitHubClient
    import time
    branch = f"feature/backlog-item-{time.strftime('%Y%m%d-%H%M%S')}"
    try:
        gh = GitHubClient()
        pr = gh.open_pr(branch=branch,
                        title=_first_line(artifacts["po"], "## Epic") or "Implement backlog item",
                        body="Implements the approved backlog.\n\n(Generated by the Code phase.)",
                        files={"app/generated_change.md": artifacts["code"]})
        state["pr_number"] = pr.number
        print(f"  -> GitHub PR opened: {pr.url}" + (" (dry-run)" if pr.dry_run else ""))
    except SystemExit as e:
        print(f"  -> GitHub PR skipped: {e}")
    except Exception as e:
        print(f"  -> GitHub PR error (continuing): {e}")

def after_pr(artifacts, state):
    from github_client import GitHubClient
    review = artifacts["pr"]
    request_changes = "REQUEST CHANGES" in review.upper()
    try:
        gh = GitHubClient()
        gh.post_findings(state.get("pr_number"), summary=review, request_changes=request_changes)
        print(f"  -> GitHub: review posted ({'REQUEST_CHANGES' if request_changes else 'COMMENT'})")
        return request_changes
    except SystemExit as e:
        print(f"  -> GitHub review skipped: {e}")
        return request_changes

import re
def _norm(s):
    return s.strip().lstrip("#*").strip().rstrip("*").strip().lower()

def _first_line(md, header):
    """Find an epic/heading title. Handles '## Epic', '**Epic**', 'Epic:' etc."""
    key = header.replace("#", "").strip().lower()
    lines = md.splitlines()
    for i, l in enumerate(lines):
        if _norm(l).startswith(key):
            after = re.split(key, l, flags=re.I)[-1].strip(" *:#")
            if after:
                return after
            for nxt in lines[i+1:]:
                if nxt.strip():
                    return nxt.strip().lstrip("-*# ").strip()
    return None

def _bullets(md, header):
    """Extract clean story titles under a heading. Handles '1. **Title** - desc',
    trailing bold markers, and title/description on the same line."""
    key = header.replace("#", "").strip().lower()
    out, grab = [], False
    for l in md.splitlines():
        n = _norm(l)
        if n.startswith(key):
            grab = True
            continue
        if grab and (n.startswith("acceptance") or n.startswith("out of scope") or (l.strip().startswith("#") and not l.strip().lstrip("#").strip()[:1].isdigit())):
            break
        if grab:
            title = None
            m = re.match(r"\s*\d+\.\s*(.+)$", l)                 # "1. anything"
            if m:
                title = m.group(1)
            elif l.strip().startswith(("-", "*")) and not l.strip().startswith("**"):
                title = l.strip().lstrip("-* ").strip()
            if title:
                # take the bolded title if present: **Title**
                b = re.search(r"\*\*(.+?)\*\*", title)
                if b:
                    title = b.group(1)
                # otherwise cut at the first dash / em-dash (title - description)
                else:
                    title = re.split(r"\s[-–—]\s", title)[0]
                title = title.strip().strip("*").strip()
                if title:
                    out.append(title)
    return out or ["Primary story"]

def build_ctx(key, artifacts, transcript):
    parts = []
    if key == "intake": parts.append(transcript)
    for p in INPUTS.get(key, []):
        if p in artifacts: parts.append(artifacts[p])
    ctx = "\n\n".join(x for x in parts if x).strip()
    # keep multi-input phases (pr, release) under the free-tier ~8k TPM cap:
    # truncate to ~stay well under budget (rough 4 chars/token heuristic).
    cap = {"pr": 14000, "release": 9000, "test": 14000}.get(key)
    if cap and len(ctx) > cap:
        ctx = ctx[:cap] + "\n\n...[trimmed to fit model context]..."
    return ctx

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="infile", default="demo/transcript.txt")
    ap.add_argument("--auto", action="store_true")
    args = ap.parse_args()
    transcript = open(args.infile, encoding="utf-8").read()
    print(f"Pipeline: {' -> '.join(agents.ORDER)}   |   model={llm.provider()}:{llm.model()}")

    artifacts, state = {}, {}
    for i, key in enumerate(agents.ORDER):
        a = agents.REGISTRY[key]
        while True:
            print(f"\n>> [{i+1}/6] {a.title} ...")
            art = a.run(build_ctx(key, artifacts, transcript))
            d = gate(a, args.auto)
            if d == "q": print("\nAborted."); return
            if d == "r": continue
            break
        artifacts[key] = art
        open(f"{i:02d}_{key}.md", "w", encoding="utf-8").write(art)
        # integration hooks AFTER the gate
        if key == "po":   after_po(artifacts)
        if key == "code": after_code(artifacts, state)
        if key == "pr":
            changes = after_pr(artifacts, state)
            if not changes and not args.auto:
                if input("  Merge the PR? [y/N] > ").strip().lower() == "y":
                    from github_client import GitHubClient
                    print("  -> merged:", GitHubClient().merge_pr(state.get("pr_number")))
    print("\nDone. Artifacts: " + ", ".join(f"{i:02d}_{k}.md" for i,k in enumerate(agents.ORDER)))

if __name__ == "__main__":
    main()
